name: Auto-Release ZIP on Main Update

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予创建标签和发布版本的权限

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史用于git archive

    - name: Create ZIP Archive
      run: git archive --format zip --output WordPress-6.8.1.zip HEAD

    - name: Force Update Release Tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -f WordPress-6.8.1
        git push origin autorelease --force

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: autorelease  # 使用固定标签名称
        files: WordPress-6.8.1.zip
        replace_existing: true  # 替换现有版本
        generate_release_notes: false  # 不生成发布说明
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
